# Generated by Django 6.0 on 2026-01-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_payment_client_alter_payment_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
