# Generated by Django 6.0 on 2026-01-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_sale_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
